#!/usr/bin/bash

## set width and height
w="$(tput cols)"
h="$(( $(tput lines) * 2 ))"

## options "rgb24" "rgb565"
pix_fmt="${2:-rgb24}"

clear

ffmpeg -i "$1" -f alsa default -vf "scale=w=${w:-192}:h=${h:-108}" -vcodec rawvideo -f rawvideo -pix_fmt "$pix_fmt" - 2>/dev/null | LC_ALL=C gawk -v vwidth="${w:-192}" -v vheight="${h:-108}" -v pix_fmt="${pix_fmt:-rgb24}" -f ./awk-play.gawk
