#!/usr/bin/bash

## set width and height
#w="$(tput cols)"
#h="$(( $(tput lines) * 2 ))"

clear

#ffmpeg -i "$1" -f alsa default -vf "scale=w=192:h=108" -vcodec rawvideo -f rawvideo -pix_fmt rgb565 - | LC_ALL=C gawk -f ./awk-play.gawk
ffmpeg -i "$1" -vf "scale=w=${w:-192}:h=${h:-108}" -vcodec rawvideo -f rawvideo -pix_fmt rgb565 - 2>/dev/null | LC_ALL=C gawk -v vwidth="${w:-192}" -v vheight="${h:-108}" -f ./awk-play.gawk
