#!/usr/bin/bash

clear

## set width and height
#w="$(tput cols)"
#h="$(( $(tput lines) * 2 ))"

## set fixed size
size=10

## tv aspect ratio 16:9
#w=$(( 16 * size ))
#h=$((  9 * size ))
## movie aspect ratio 21:9
w=$(( 21 * size ))
h=$((  9 * size ))

## options "rgb8" (8-bit) "rgb565" (16 bit) "rgb24" (24 bit)
pix_fmt="${2:-rgb24}"

## number of decoding threads
threads="${3:-2}"

## ffmpeg options
ffopts=( -f alsa default -vf "scale=w=${w:-160}:h=${h:-90}" -vcodec rawvideo -f rawvideo -pix_fmt "$pix_fmt" )

## awk options, needs `-b` or `LC_ALL=C` to parse byte-characters and not multi-byte characters
awkopts=( -b -v width="${w:-160}" -v height="${h:-90}" -v pix_fmt="${pix_fmt:-rgb24}" -v threads=${threads:-2} )

## start ffmpeg conversion and start displaying video
ffmpeg -ss 25 -i "$1" "${ffopts[@]}" - 2>/dev/null | ./awk-play.gawk "${awkopts[@]}"
